//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.04 at 06:00:51 PM CST 
//


package utils.rakuten.classfromxsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the utils.rakuten.classfromxsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Information_QNAME = new QName("", "information");
    private final static QName _Keywords_QNAME = new QName("", "keywords");
    private final static QName _Buy_QNAME = new QName("", "buy");
    private final static QName _Pixel_QNAME = new QName("", "pixel");
    private final static QName _M1_QNAME = new QName("", "m1");
    private final static QName _Secondary_QNAME = new QName("", "secondary");
    private final static QName _ProductImage_QNAME = new QName("", "productImage");
    private final static QName _Type_QNAME = new QName("", "type");
    private final static QName _Long_QNAME = new QName("", "long");
    private final static QName _Upc_QNAME = new QName("", "upc");
    private final static QName _Currency_QNAME = new QName("", "currency");
    private final static QName _CreatedOn_QNAME = new QName("", "createdOn");
    private final static QName _Short_QNAME = new QName("", "short");
    private final static QName _Amount_QNAME = new QName("", "amount");
    private final static QName _Modification_QNAME = new QName("", "modification");
    private final static QName _Primary_QNAME = new QName("", "primary");
    private final static QName _Brand_QNAME = new QName("", "brand");
    private final static QName _MerchantName_QNAME = new QName("", "merchantName");
    private final static QName _MerchantId_QNAME = new QName("", "merchantId");
    private final static QName _NumberOfProducts_QNAME = new QName("", "numberOfProducts");
    private final static QName _Attribute1_QNAME = new QName("", "attribute1");
    private final static QName _Retail_QNAME = new QName("", "retail");
    private final static QName _Availability_QNAME = new QName("", "availability");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: utils.rakuten.classfromxsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Trailer }
     * 
     */
    public Trailer createTrailer() {
        return new Trailer();
    }

    /**
     * Create an instance of {@link Shipping }
     * 
     */
    public Shipping createShipping() {
        return new Shipping();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link URL }
     * 
     */
    public URL createURL() {
        return new URL();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Merchandiser }
     * 
     */
    public Merchandiser createMerchandiser() {
        return new Merchandiser();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link Discount }
     * 
     */
    public Discount createDiscount() {
        return new Discount();
    }

    /**
     * Create an instance of {@link Price }
     * 
     */
    public Price createPrice() {
        return new Price();
    }

    /**
     * Create an instance of {@link AttributeClass }
     * 
     */
    public AttributeClass createAttributeClass() {
        return new AttributeClass();
    }

    /**
     * Create an instance of {@link Sale }
     * 
     */
    public Sale createSale() {
        return new Sale();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "information")
    public JAXBElement<String> createInformation(String value) {
        return new JAXBElement<String>(_Information_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "keywords")
    public JAXBElement<String> createKeywords(String value) {
        return new JAXBElement<String>(_Keywords_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "buy")
    public JAXBElement<String> createBuy(String value) {
        return new JAXBElement<String>(_Buy_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pixel")
    public JAXBElement<String> createPixel(String value) {
        return new JAXBElement<String>(_Pixel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "m1")
    public JAXBElement<String> createM1(String value) {
        return new JAXBElement<String>(_M1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "secondary")
    public JAXBElement<String> createSecondary(String value) {
        return new JAXBElement<String>(_Secondary_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "productImage")
    public JAXBElement<String> createProductImage(String value) {
        return new JAXBElement<String>(_ProductImage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type")
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "long")
    public JAXBElement<String> createLong(String value) {
        return new JAXBElement<String>(_Long_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "upc")
    public JAXBElement<String> createUpc(String value) {
        return new JAXBElement<String>(_Upc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "currency")
    public JAXBElement<String> createCurrency(String value) {
        return new JAXBElement<String>(_Currency_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "createdOn")
    public JAXBElement<String> createCreatedOn(String value) {
        return new JAXBElement<String>(_CreatedOn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "short")
    public JAXBElement<String> createShort(String value) {
        return new JAXBElement<String>(_Short_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "amount")
    public JAXBElement<String> createAmount(String value) {
        return new JAXBElement<String>(_Amount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "modification")
    public JAXBElement<String> createModification(String value) {
        return new JAXBElement<String>(_Modification_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "primary")
    public JAXBElement<String> createPrimary(String value) {
        return new JAXBElement<String>(_Primary_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "brand")
    public JAXBElement<String> createBrand(String value) {
        return new JAXBElement<String>(_Brand_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "merchantName")
    public JAXBElement<String> createMerchantName(String value) {
        return new JAXBElement<String>(_MerchantName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "merchantId")
    public JAXBElement<String> createMerchantId(String value) {
        return new JAXBElement<String>(_MerchantId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "numberOfProducts")
    public JAXBElement<String> createNumberOfProducts(String value) {
        return new JAXBElement<String>(_NumberOfProducts_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "attribute1")
    public JAXBElement<String> createAttribute1(String value) {
        return new JAXBElement<String>(_Attribute1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "retail")
    public JAXBElement<String> createRetail(String value) {
        return new JAXBElement<String>(_Retail_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "availability")
    public JAXBElement<String> createAvailability(String value) {
        return new JAXBElement<String>(_Availability_QNAME, String.class, null, value);
    }

}
