//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.04 at 06:00:51 PM CST 
//


package utils.rakuten.classfromxsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}category"/>
 *         &lt;element ref="{}URL"/>
 *         &lt;element ref="{}description"/>
 *         &lt;element ref="{}discount"/>
 *         &lt;element ref="{}price"/>
 *         &lt;element ref="{}brand"/>
 *         &lt;element ref="{}shipping"/>
 *         &lt;element ref="{}keywords"/>
 *         &lt;element ref="{}upc"/>
 *         &lt;element ref="{}m1"/>
 *         &lt;element ref="{}pixel"/>
 *         &lt;element ref="{}attributeClass"/>
 *         &lt;element ref="{}modification"/>
 *       &lt;/sequence>
 *       &lt;attribute name="manufacturer_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="part_number" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="product_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sku_number" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "category",
    "url",
    "description",
    "discount",
    "price",
    "brand",
    "shipping",
    "keywords",
    "upc",
    "m1",
    "pixel",
    "attributeClass",
    "modification"
})
@XmlRootElement(name = "product")
public class Product {

    @XmlElement(required = true)
    protected Category category;
    @XmlElement(name = "URL", required = true)
    protected URL url;
    @XmlElement(required = true)
    protected Description description;
    @XmlElement(required = true)
    protected Discount discount;
    @XmlElement(required = true)
    protected Price price;
    @XmlElement(required = true)
    protected String brand;
    @XmlElement(required = true)
    protected Shipping shipping;
    @XmlElement(required = true)
    protected String keywords;
    @XmlElement(required = true)
    protected String upc;
    @XmlElement(required = true)
    protected String m1;
    @XmlElement(required = true)
    protected String pixel;
    @XmlElement(required = true)
    protected AttributeClass attributeClass;
    @XmlElement(required = true)
    protected String modification;
    @XmlAttribute(name = "manufacturer_name")
    protected String manufacturerName;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "part_number")
    protected String partNumber;
    @XmlAttribute(name = "product_id")
    protected String productId;
    @XmlAttribute(name = "sku_number")
    protected String skuNumber;

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link Category }
     *     
     */
    public Category getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link Category }
     *     
     */
    public void setCategory(Category value) {
        this.category = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link URL }
     *     
     */
    public URL getURL() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link URL }
     *     
     */
    public void setURL(URL value) {
        this.url = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Description }
     *     
     */
    public Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description }
     *     
     */
    public void setDescription(Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the discount property.
     * 
     * @return
     *     possible object is
     *     {@link Discount }
     *     
     */
    public Discount getDiscount() {
        return discount;
    }

    /**
     * Sets the value of the discount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Discount }
     *     
     */
    public void setDiscount(Discount value) {
        this.discount = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link Price }
     *     
     */
    public Price getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link Price }
     *     
     */
    public void setPrice(Price value) {
        this.price = value;
    }

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrand(String value) {
        this.brand = value;
    }

    /**
     * Gets the value of the shipping property.
     * 
     * @return
     *     possible object is
     *     {@link Shipping }
     *     
     */
    public Shipping getShipping() {
        return shipping;
    }

    /**
     * Sets the value of the shipping property.
     * 
     * @param value
     *     allowed object is
     *     {@link Shipping }
     *     
     */
    public void setShipping(Shipping value) {
        this.shipping = value;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * Sets the value of the keywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeywords(String value) {
        this.keywords = value;
    }

    /**
     * Gets the value of the upc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpc() {
        return upc;
    }

    /**
     * Sets the value of the upc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpc(String value) {
        this.upc = value;
    }

    /**
     * Gets the value of the m1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getM1() {
        return m1;
    }

    /**
     * Sets the value of the m1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setM1(String value) {
        this.m1 = value;
    }

    /**
     * Gets the value of the pixel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPixel() {
        return pixel;
    }

    /**
     * Sets the value of the pixel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPixel(String value) {
        this.pixel = value;
    }

    /**
     * Gets the value of the attributeClass property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeClass }
     *     
     */
    public AttributeClass getAttributeClass() {
        return attributeClass;
    }

    /**
     * Sets the value of the attributeClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeClass }
     *     
     */
    public void setAttributeClass(AttributeClass value) {
        this.attributeClass = value;
    }

    /**
     * Gets the value of the modification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModification() {
        return modification;
    }

    /**
     * Sets the value of the modification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModification(String value) {
        this.modification = value;
    }

    /**
     * Gets the value of the manufacturerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturerName() {
        return manufacturerName;
    }

    /**
     * Sets the value of the manufacturerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturerName(String value) {
        this.manufacturerName = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the partNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartNumber() {
        return partNumber;
    }

    /**
     * Sets the value of the partNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartNumber(String value) {
        this.partNumber = value;
    }

    /**
     * Gets the value of the productId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductId(String value) {
        this.productId = value;
    }

    /**
     * Gets the value of the skuNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkuNumber() {
        return skuNumber;
    }

    /**
     * Sets the value of the skuNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkuNumber(String value) {
        this.skuNumber = value;
    }

}
