//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.08 at 02:33:52 PM CST 
//


package utils.impactradius.classfromxsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Product" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Unique_Merchant_SKU" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Product_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Product_URL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Image_URL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Current_Price" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Stock_Availability" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Condition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="EAN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="UPC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ISBN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="MPN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Shipping_Rate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Original_Price" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Manufacturer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Product_Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Product_Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Category_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Alternative_Image_URL_1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Parent_SKU" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Parent_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Color" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Size" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Product_Weight" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Shipping_Weight" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Weight_Unit_of_Measure" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Bundle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "product"
})
@XmlRootElement(name = "Products")
public class Products {

    @XmlElement(name = "Product")
    protected List<Products.Product> product;

    /**
     * Gets the value of the product property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the product property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProduct().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Products.Product }
     * 
     * 
     */
    public List<Products.Product> getProduct() {
        if (product == null) {
            product = new ArrayList<Products.Product>();
        }
        return this.product;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Unique_Merchant_SKU" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Product_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Product_URL" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Image_URL" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Current_Price" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Stock_Availability" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Condition" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="EAN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="UPC" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ISBN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="MPN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Shipping_Rate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Original_Price" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Manufacturer" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Product_Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Product_Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Category_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Alternative_Image_URL_1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Parent_SKU" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Parent_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Color" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Size" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Product_Weight" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Shipping_Weight" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Weight_Unit_of_Measure" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Bundle" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "uniqueMerchantSKU",
        "productName",
        "productURL",
        "imageURL",
        "currentPrice",
        "stockAvailability",
        "condition",
        "ean",
        "upc",
        "isbn",
        "mpn",
        "shippingRate",
        "originalPrice",
        "manufacturer",
        "productDescription",
        "productType",
        "category",
        "categoryID",
        "alternativeImageURL1",
        "parentSKU",
        "parentName",
        "gender",
        "color",
        "size",
        "productWeight",
        "shippingWeight",
        "weightUnitOfMeasure",
        "bundle"
    })
    public static class Product {

        @XmlElement(name = "Unique_Merchant_SKU", required = true)
        protected String uniqueMerchantSKU;
        @XmlElement(name = "Product_Name", required = true)
        protected String productName;
        @XmlElement(name = "Product_URL", required = true)
        protected String productURL;
        @XmlElement(name = "Image_URL", required = true)
        protected String imageURL;
        @XmlElement(name = "Current_Price", required = true)
        protected String currentPrice;
        @XmlElement(name = "Stock_Availability", required = true)
        protected String stockAvailability;
        @XmlElement(name = "Condition", required = true)
        protected String condition;
        @XmlElement(name = "EAN", required = true)
        protected String ean;
        @XmlElement(name = "UPC", required = true)
        protected String upc;
        @XmlElement(name = "ISBN", required = true)
        protected String isbn;
        @XmlElement(name = "MPN", required = true)
        protected String mpn;
        @XmlElement(name = "Shipping_Rate")
        protected String shippingRate;
        @XmlElement(name = "Original_Price", required = true)
        protected String originalPrice;
        @XmlElement(name = "Manufacturer", required = true)
        protected String manufacturer;
        @XmlElement(name = "Product_Description", required = true)
        protected String productDescription;
        @XmlElement(name = "Product_Type", required = true)
        protected String productType;
        @XmlElement(name = "Category", required = true)
        protected String category;
        @XmlElement(name = "Category_ID", required = true)
        protected String categoryID;
        @XmlElement(name = "Alternative_Image_URL_1", required = true)
        protected String alternativeImageURL1;
        @XmlElement(name = "Parent_SKU", required = true)
        protected String parentSKU;
        @XmlElement(name = "Parent_Name", required = true)
        protected String parentName;
        @XmlElement(name = "Gender")
        protected String gender;
        @XmlElement(name = "Color")
        protected String color;
        @XmlElement(name = "Size")
        protected String size;
        @XmlElement(name = "Product_Weight", required = true)
        protected String productWeight;
        @XmlElement(name = "Shipping_Weight", required = true)
        protected String shippingWeight;
        @XmlElement(name = "Weight_Unit_of_Measure", required = true)
        protected String weightUnitOfMeasure;
        @XmlElement(name = "Bundle", required = true)
        protected String bundle;

        /**
         * Gets the value of the uniqueMerchantSKU property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUniqueMerchantSKU() {
            return uniqueMerchantSKU;
        }

        /**
         * Sets the value of the uniqueMerchantSKU property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUniqueMerchantSKU(String value) {
            this.uniqueMerchantSKU = value;
        }

        /**
         * Gets the value of the productName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductName() {
            return productName;
        }

        /**
         * Sets the value of the productName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductName(String value) {
            this.productName = value;
        }

        /**
         * Gets the value of the productURL property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductURL() {
            return productURL;
        }

        /**
         * Sets the value of the productURL property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductURL(String value) {
            this.productURL = value;
        }

        /**
         * Gets the value of the imageURL property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getImageURL() {
            return imageURL;
        }

        /**
         * Sets the value of the imageURL property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImageURL(String value) {
            this.imageURL = value;
        }

        /**
         * Gets the value of the currentPrice property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrentPrice() {
            return currentPrice;
        }

        /**
         * Sets the value of the currentPrice property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrentPrice(String value) {
            this.currentPrice = value;
        }

        /**
         * Gets the value of the stockAvailability property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStockAvailability() {
            return stockAvailability;
        }

        /**
         * Sets the value of the stockAvailability property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStockAvailability(String value) {
            this.stockAvailability = value;
        }

        /**
         * Gets the value of the condition property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCondition() {
            return condition;
        }

        /**
         * Sets the value of the condition property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCondition(String value) {
            this.condition = value;
        }

        /**
         * Gets the value of the ean property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEAN() {
            return ean;
        }

        /**
         * Sets the value of the ean property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEAN(String value) {
            this.ean = value;
        }

        /**
         * Gets the value of the upc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUPC() {
            return upc;
        }

        /**
         * Sets the value of the upc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUPC(String value) {
            this.upc = value;
        }

        /**
         * Gets the value of the isbn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getISBN() {
            return isbn;
        }

        /**
         * Sets the value of the isbn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setISBN(String value) {
            this.isbn = value;
        }

        /**
         * Gets the value of the mpn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMPN() {
            return mpn;
        }

        /**
         * Sets the value of the mpn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMPN(String value) {
            this.mpn = value;
        }

        /**
         * Gets the value of the shippingRate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShippingRate() {
            return shippingRate;
        }

        /**
         * Sets the value of the shippingRate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShippingRate(String value) {
            this.shippingRate = value;
        }

        /**
         * Gets the value of the originalPrice property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOriginalPrice() {
            return originalPrice;
        }

        /**
         * Sets the value of the originalPrice property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOriginalPrice(String value) {
            this.originalPrice = value;
        }

        /**
         * Gets the value of the manufacturer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getManufacturer() {
            return manufacturer;
        }

        /**
         * Sets the value of the manufacturer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setManufacturer(String value) {
            this.manufacturer = value;
        }

        /**
         * Gets the value of the productDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductDescription() {
            return productDescription;
        }

        /**
         * Sets the value of the productDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductDescription(String value) {
            this.productDescription = value;
        }

        /**
         * Gets the value of the productType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductType() {
            return productType;
        }

        /**
         * Sets the value of the productType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductType(String value) {
            this.productType = value;
        }

        /**
         * Gets the value of the category property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCategory() {
            return category;
        }

        /**
         * Sets the value of the category property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCategory(String value) {
            this.category = value;
        }

        /**
         * Gets the value of the categoryID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCategoryID() {
            return categoryID;
        }

        /**
         * Sets the value of the categoryID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCategoryID(String value) {
            this.categoryID = value;
        }

        /**
         * Gets the value of the alternativeImageURL1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAlternativeImageURL1() {
            return alternativeImageURL1;
        }

        /**
         * Sets the value of the alternativeImageURL1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAlternativeImageURL1(String value) {
            this.alternativeImageURL1 = value;
        }

        /**
         * Gets the value of the parentSKU property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getParentSKU() {
            return parentSKU;
        }

        /**
         * Sets the value of the parentSKU property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setParentSKU(String value) {
            this.parentSKU = value;
        }

        /**
         * Gets the value of the parentName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getParentName() {
            return parentName;
        }

        /**
         * Sets the value of the parentName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setParentName(String value) {
            this.parentName = value;
        }

        /**
         * Gets the value of the gender property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGender() {
            return gender;
        }

        /**
         * Sets the value of the gender property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGender(String value) {
            this.gender = value;
        }

        /**
         * Gets the value of the color property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getColor() {
            return color;
        }

        /**
         * Sets the value of the color property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setColor(String value) {
            this.color = value;
        }

        /**
         * Gets the value of the size property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSize() {
            return size;
        }

        /**
         * Sets the value of the size property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSize(String value) {
            this.size = value;
        }

        /**
         * Gets the value of the productWeight property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductWeight() {
            return productWeight;
        }

        /**
         * Sets the value of the productWeight property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductWeight(String value) {
            this.productWeight = value;
        }

        /**
         * Gets the value of the shippingWeight property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShippingWeight() {
            return shippingWeight;
        }

        /**
         * Sets the value of the shippingWeight property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShippingWeight(String value) {
            this.shippingWeight = value;
        }

        /**
         * Gets the value of the weightUnitOfMeasure property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWeightUnitOfMeasure() {
            return weightUnitOfMeasure;
        }

        /**
         * Sets the value of the weightUnitOfMeasure property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWeightUnitOfMeasure(String value) {
            this.weightUnitOfMeasure = value;
        }

        /**
         * Gets the value of the bundle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBundle() {
            return bundle;
        }

        /**
         * Sets the value of the bundle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBundle(String value) {
            this.bundle = value;
        }

    }

}
